### ISSUE TITLE
dependencies for modules

### ISSUE THREAD

**Issue by SebRut** [twisterghost/jankbot#21]
It should be relatively easy to let the script check all module dirs for package.json files and run "npm install bot_modules/moddir/"

**Comment by twisterghost** [comment]
Absolutely. I've been tinkering with adding native module installation through jankbot, and this will be a part of it. I'll leave this issue open until a PR is resolved with that implementation.

**Comment by twisterghost** [comment]
Upon some further thought, I'm going to look into using NPM to start controlling the installation of Jankbot modules. Jankbot will scan the node_modules directory for subdirectories containing a `module.json` and load it if possible. This would also allow for modules to define their own dependencies (in theory)

**Comment by twisterghost** [comment]
Added support for loading jankbot modules from `node_modules` in baf06febf02d63df3d13a48a6b0f953948f4f0d1

This means Jankbot modules can now be published to npm's registry and specify their own dependencies, and can be installed via npm.

I will be prepping existing JankDota modules to be published to npm soon. Support for legacy bot module loading is still available.
