### ISSUE TITLE
Error Windows 7

### ISSUE THREAD

**Issue by singhh93** [twisterghost/jankbot#23]
Got all pre-requried files installed and uninstalled older version or incorrect ones...

Cannot compile

 protobuf@0.11.0 install: `node-gyp rebuild`
 Exit status 1

**Comment by twisterghost** [comment]
Do you have any more of the error output that you can give? Any more info about your environment?

**Comment by singhh93** [comment]
[npm-debug.txt](https://github.com/twisterghost/jankbot/files/59959/npm-debug.txt)

**Comment by singhh93** [comment]
[npm-debug.txt](https://github.com/twisterghost/jankbot/files/59961/npm-debug.txt)

**Comment by twisterghost** [comment]
I'm looking into it, but if you can give me information about what you have installed, that might help me help you out. While possible to run Jankbot on Windows, it does take some extra setup. You may need to check your path variables and be sure the openSSL executable is there.

**Comment by twisterghost** [comment]
I was able to successfully install and run jankbot on windows (Although its windows 10, I can try as well on a windows 7 box) by installing openSSL, python2.7, and [this version  of VSC++](http://go.microsoft.com/?linkid=9816758), then installing `node-gyp` globally with `npm install -g node-gyp` and running the `npm install` command for Jankbot.

One note is that I had to specifically use Node version `0.10.40` and install node-gyp on that version of node, and I was sure to use visual studio 2012 (2010 should work too) instead of 2013, as the ursa package (the one that needs all these dependencies) does not support being built with 2013, but does with 2010 and 2012.

Double check all of your dependencies, and be sure to have python and openssl in your PATH variable, then try removing the `node_modules` directory from jankbot and try installing again.

**Comment by singhh93** [comment]
Appreciate that in depth response man! Now I can try that when I get home tonight and report back.
Awesome project you got here. Keep it up, can see great potential to be on the top.

**Comment by twisterghost** [comment]
Thanks for the kind words. Let me know how it goes, hope this gets figured out.

**Comment by singhh93** [comment]
Double check all of your dependencies, and be sure to have python and openssl in your PATH variable, then try removing the node_modules directory from jankbot and try installing again.


PATH Variables
What should they look like under the settings < control panel

**Comment by singhh93** [comment]
> protobuf@0.11.0 install c:\Users\Max\dota2\node_modules\dota2\node_modules\pro
tobuf
> node-gyp rebuild

npm ERR! ursa@0.9.1 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ursa@0.9.1 install script.
npm ERR! This is most likely a problem with the ursa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ursa
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd c:\Users\Max\dota2
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! syscall spawn
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! not ok code 0

**Comment by singhh93** [comment]
Removed;
Visual C++ Redistributable for Visual Studio 2015..
Should I re-enable?


--- New error after restarting computer after double checking..


npm ERR! ref@1.3.1 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ref@1.3.1 install script.
npm ERR! This is most likely a problem with the ref package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ref
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\Max\dota2
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! syscall spawn
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! not ok code 0

C:\Users\Max\dota2>

**Comment by twisterghost** [comment]
Did you install a 2010 or 2012 version of the C++ visual studio redistributable? 

For the path variable, make sure it contains the directory that has the openSSL executable in it. For me, I installed it to `C:\programs\openssl` so my PATH looks like `C:\blah\blah;C:\something\else;C:\programs\openssl`

**Comment by singhh93** [comment]
Okay; paths for python and openssl are correctly set. 
Triple checking dependencies, making sure no overlapping installs.

**Comment by singhh93** [comment]
https://gyazo.com/06037fc19e19325edf3d60d1214a8ce9 (x86 version of x64 at bottom)
OpenSSL
Python 2.7
Node 0.10.40
-npm install node gyp done -

**Comment by singhh93** [comment]
After trying different .msi for x86 and x64 and running as admin, opening up folders from attributes and such. Deleting APPDATA and all folders relating to npm / nodejs and reinstalling 0.10.40 

Hmmph

**Comment by twisterghost** [comment]
Be sure to use the same bitness of openssl as you have for your node
package. So if you have 64bit node, use a 64bit openssl and so on. I can
continue to try and help tomorrow.

**Comment by singhh93** [comment]
I think I maybe have both versions possibly installed, problem? (OpenSSL)

**Comment by twisterghost** [comment]
No, Jankbot does not require a GPU. I would advocate for using a server, as it means that Jankbot isn't tied to your computer being online, and Jankbot was build primarily to run on Linux. I personally suggest [Linode](https://www.linode.com/pricing), as their basic offering is a good value.

Just one last check though, do you also have the visual studio 2010 link provided by the ursa `README` installed, as well as the 64-bit sdk and compiler update linked in their repository?

Quoting from their repo: 

- Windows XP/Vista/7:
    - `Microsoft Visual Studio C++ 2010` ([Express](http://go.microsoft.com/?linkid=9709949) version works well)
        - For 64-bit builds of node and native modules you will _**also**_ need the [Windows 7 64-bit SDK](http://www.microsoft.com/en-us/download/details.aspx?id=8279)
        - If you get errors that the 64-bit compilers are not installed you may also need the [compiler update for the Windows SDK 7.1](http://www.microsoft.com/en-us/download/details.aspx?id=4422)

**Comment by singhh93** [comment]
I no longer have 2010
I have,
![image](https://cloud.githubusercontent.com/assets/16258416/11767689/bd546320-a182-11e5-8065-7b666e97ffff.png)

+the 
Windows 7 64-bit SDK
+ the compiler update for the Windows SDK 7.1


^ Which should I keep or remove along side with getting the C++ 2010 Express Version

**Comment by singhh93** [comment]
Yeah. I am going to attempt it through today. Then most likely do linux if not. This is just a way for me to write a simple program to work along a website. Like a game panel :)

**Comment by singhh93** [comment]
Doing this under node.js command prompt ran as administrator. 
Restarted computer same error; won't spit out a log file anymore.

Same errors.

**Comment by twisterghost** [comment]
Jankbot doesn't take much memory or cpu to run well. It can run with a pretty heavy friend load on under 256mb of ram and 1 cpu.  The 1st tier linode package is more than enough. An amazon EC2 instance could probably work fine, too, though I haven't tried that personally.

I'm going to close this issue, as I believe it is an environment problem and not a problem with Jankbot directly. If you want to keep in contact for help, you can email me directly at twisterghost@gmail.com, and I'll be happy to help you get set up.
