### ISSUE TITLE
Upgrade node-dota2 to support Reborn

### ISSUE THREAD

**Issue by twisterghost** [twisterghost/jankbot#26]
Dependency version update and refactoring / migration to the new `node-dota2` package to support Reborn. Currently, the `dota2` core module of Jankbot doesn't allow for proper Reborn support, and seeing as the client is now only Reborn, this should probably be updated.

**Comment by twisterghost** [comment]
A trello card has been made to track the progress of this issue: https://trello.com/c/3hRjxvcN/40-upgrade-node-dota2-to-support-reborn

**Comment by beatyt** [comment]
Not sure if I should comment this here or on trello, but I have jankbot working with node-dota: 1.0.1 and node-steam: 1.4.0.  Does node-dota2 being version 1.0.1 = proper Reborn support?  I manually tested and was able to make jankbot launch dota 2 and accept a party invite.

I'll open a PR later today so you can see what I changed and then go from there.

**Comment by twisterghost** [comment]
Here is fine. Thats good news for sure. I had plans to do a large refactor with an update of the node-steam dependency, but I would also like to see what you have.
