### ISSUE TITLE
dota2.client is undefined

### ISSUE THREAD

**Issue by fultonm** [twisterghost/jankbot#30]
dota2.launch(() => {
    console.log(dota2.client)
  })

outputs undefined. It could be I'm using the file wrong. I did add a callback to the launch method for testing. No matter how I use it it's undefined. How can I get access to the node-dota2 functions?

**Comment by twisterghost** [comment]
Ah, looks like its actually exposing `dota2` instead of `client`. Thats totally my bad. I'll push an update to fix that, but for now I've updated the docs to represent the code better.

It'd look like:

```
var jankbotDota2 = require ('./core/dota2');
jankbotDota2.launch();
console.log(jankbotDota2.dota2); // here is the node-dota2 instance
```

**Comment by fultonm** [comment]
I'm still confused:
```
let dota2 = require('./core/dota2.js');

dota2.launch(() => {
   console.log('Exposed properties of ./core/dota2')
   console.log(dota2)
 })

// Dota2 is ready to do things.
// Exposed properties of ./core/dota2
// { init: [Function],
//   launch: [Function],
//   gg: [Function],
//   client: undefined }
```

Also after this is working it is possible to access the chat in-game (not the steam chat, but the Dota 2 chat channels)

**Comment by twisterghost** [comment]
`dota2.launch()` doesn't take a callback, but I have pushed a fix, and you should now be able to get the `node-dota2` client using `dota2.getClient()` from the jankbot core module.

I have also updated the wiki page to match the new functionality: https://github.com/twisterghost/jankbot/wiki/Core-Module:-dota2.js

So, you should be able to do the following:

```javascript
const dota2 = require('./core/dota2.js');

dota2.launch();

const client = dota2.getClient();
client.on('ready', () => {
  // Some code using `client` here!
});
```

You'll need the [latest release](https://github.com/twisterghost/jankbot/releases/tag/v3.1.0) for this to work.

**Comment by twisterghost** [comment]
Let me know if this works for you, and I'll close the issue. Thanks for bringing this up!
